name = "rsshub"
main = "src/index.ts"
compatibility_date = "2023-04-26"
env = { }

[triggers]
crons = [ ]

[build]
command = "npx esbuild src/index.ts --bundle --outfile=dist/worker.js --format=esm --platform=neutral"
